language: 'elixir'

elixir: 1.8.1
otp_release: 21.3

matrix:
  include:
  - otp_release: 19.3
    elixir: 1.6.6
  - otp_release: 20.0
    elixir: 1.6.5
  - otp_release: 20.2
    elixir: 1.7.4

cache:
  directories:
  - _build
  - deps

script:
  - ./priv/scripts/ci-check.sh
  - mix coveralls.travis
